name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: '3.3.0'

jobs:
  build-and-push:
    runs-on: bigger_linux
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: set up qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: Build and push for ARM and AMD64
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        provenance: false
        tags: |
          ghcr.io/noipcom/noip-duc:latest
          ghcr.io/noipcom/noip-duc:${{ env.VERSION }}
          noipcom/noip-duc:latest
          noipcom/noip-duc:${{ env.VERSION }}
